apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - migration-job.yaml
configMapGenerator:
  - name: trunk-api-init-scripts
    files:
      - scripts/wait-for-tcp.sh
