apiVersion: v1
kind: ConfigMap
metadata:
  name: trunk-config
  namespace: trunk-dev-tenant-3
data:
  TENANT: "tenant-3"
  NODE_ENV: "development"
  REGION: "europe-west1"
  CLOUD: "gcp"
  LOG_LEVEL: "debug"
