apiVersion: v1
kind: ConfigMap
metadata:
  name: trunk-config
  namespace: trunk-production-tenant-3
data:
  TENANT: "tenant-3"
  NODE_ENV: "production"
  REGION: "europe-west1"
  CLOUD: "gcp"
  LOG_LEVEL: "warn"
